### ISSUE TITLE
 ERROR LOADING PLUGIN homebridge-sonoff-4ch

### ISSUE THREAD

**Issue by sandrinoz600** [radebebek/homebridge-sonoff-4CH#1]
hello I installed the plugin but I receive this error,
 ERROR LOADING PLUGIN homebridge-sonoff-4ch:
[2018-1-31 15:22:12] Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-sonoff-4ch/index.js:1:77)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
 I tried to install other plugins without any errors 
what is the problem?

THx

**Comment by radebebek** [comment]
Hello, 
For this plugin you must install one more plugin :
https://www.npmjs.com/package/request

Install command:
npm install request

Best Regards,
Rade

**Comment by sandrinoz600** [comment]
hello,
I did but I always have the same error
when I install the plugin ( both request and homebridge-sonoff-4ch) I receive this error
pi@raspberrypi:~ $ npm install request
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

+ request@2.83.0
updated 1 package in 4.325s
pi@raspberrypi:~ $ npm install homebridge-sonoff-4ch
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

+ homebridge-sonoff-4ch@2.0.3
added 1 package in 3.697s
 sorry but I'm a  beginner of these applications!
B.R
Sandrino

**Comment by radebebek** [comment]
I am not sure how you can solves this problem. But this is not a problem of plugin. 
Try search internet about this problem. I find some attempts:
Try with sudo: 
1. **sudo** npm install request
Try clean cache:
1. npm cache clean --force
Or try install lasted npm:
1. npm install npm@latest -g
If you success, tell me back.

**Comment by sandrinoz600** [comment]
hi, still not working.
the strange thing is that I try to install some other plugin without error!

**Comment by sandrinoz600** [comment]
hi,
at the end after several attempts and having read countless posts I managed to make everything work.
I had to install the plugin exactly in the directory where homebridge was installed.
now everything works!
thanks for the support!
